---
apiVersion: v1
offerings:
  - name: terraform-ibm-secrets-manager-secret-group
    kind: module
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: ef8cddd2-e724-43d3-88f8-386af4f12c49
    examples:
      - name: basic
        mark_ready: true
